### ISSUE TITLE
Rerouting issue

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#261]
As we're testing for navigation these days, we've found out that sometimes the navigation suddenly starts to rerouting and then guides the user to reversed way (the navigation direction suddenly turns 180 degree and ask user to make a u-turn) even if the car is already on the correct route.
This is more likely to happen while the car is stopping at intersections, or the car is beneath the bridges or viaducts.
I thought it might be I used `setTrafficAvoidanceMode` to `dynamic`, but later on i removed this line (i believe default value is `disabled`), it was not getting better.
Can you please help? Thanks.

This was happened while the car stopped at the intersection (the car isn't moving)
 [https://bit.ly/2KEx6Fk](url)
 This happened when the car is under the viaduct: [https://www.dropbox.com/s/c5g8c3gokwgamki/10083883718389.mp4?dl=0](url)

**Comment by Merlin1stHere** [comment]
@bluesnow4425 Could you provide the coordinates of the place where this issue occurred?

**Comment by bluesnow4425** [comment]
From: 25.079266, 121.556989
To: 25.068378, 121.536426
Issue happened place: 25.072542, 121.538963

As you can see, the problem only happens in android.

**Comment by Merlin1stHere** [comment]
Hi @bluesnow4425 
I can't reproduce this issue. Which version of the SDK you use?
If you are using 3.11, consider switching to 3.12.
Also you can try to prefetch the route before navigation (by using **MapDataPrefetcher.fetchMapData**).
One more suggestion - try to enable enhanced map matcher (**ApplicationContext.enableEnhancedMapMatcher**)

**Comment by bluesnow4425** [comment]
ok. but any suggestion about when the car stops and it starts to rerouting? It's very common and almost every android user in our offie encounters this problem during test. As i observe, i think it might be positioning problem, the position indicator moves slightly from time to time, and then it starts to reroute. any possible improvement we can do to tune the behavior when the user stops to move?

**Comment by Merlin1stHere** [comment]
@bluesnow4425 I believe enhanced map matcher should fix this issue.

**Comment by bluesnow4425** [comment]
Got it. The only thing we need to do it to enable it in Application file?

**Comment by starand** [comment]
hi @bluesnow4425,
You can enable enhanced map matcher using ApplicationContext object, which is usually passed into **MapFragment.init()** or **MapEngine.init()** method.
You can see **API Changes** section in **Release Notes** document inside archive downloaded from dev portal.

```
ApplicationContext context = new ApplicationContext(getApplicationContext());
context.enableEnhancedMapMatcher(true);
```

**Comment by starand** [comment]
@bluesnow4425, is there any progress? Did you manage to solve your issue?

**Comment by bluesnow4425** [comment]
hi thanks for following up. I tried new sdk and i set enableEnhancedMapMatcher to true also. However, when car stops, frequently rerouting  is still happening. What i intend to do now is to stop rerouting when the car stops. I show previous route and ignore rerouting callback, but voice guidance still use the new route. 
Is the only way that I remove rerouteListener from NavigationManager when the car stops and reset it again when car starts to move? (I haven't try. Don't know if it works)

**Comment by Merlin1stHere** [comment]
@bluesnow4425 One more suggestion: could you try to prefetch map data for this route before navigation? **Use MapDataPrefetcher.fetchMapData(Route route, int radius)**

**Comment by starand** [comment]
If there is no clue why it happens on your side, could you try to update one of github samples and see whether this is still reproducible? In case yes, could yo please share that app with steps to reproduce? Probably the issue requires more deep investigation.

**Comment by bluesnow4425** [comment]
yes i've used prefetcher before but it costs too much network data so i turned it off.
However the issue occurs no matter prefetch or not.

I'll try to upload the code partially and paste here once it's done.

**Comment by Merlin1stHere** [comment]
@bluesnow4425 Could you provide a GPX log saved when a problem occurs?
Please see **PositioningManager.setLogType**.

**Comment by starand** [comment]
@bluesnow4425 did you manage to get logs?
